# Ruff configuration for replaykit
# https://docs.astral.sh/ruff/configuration/

# Exclude common directories
exclude = [
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    "build",
    "dist",
    "*.egg-info",
]

# Set the target Python version
target-version = "py39"

# Set line length to 88 (Black default)
line-length = 88

[lint]
# Enable common rulesets
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "N",   # pep8-naming
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "SIM", # flake8-simplify
]

# Ignore specific rules if needed
ignore = [
    "B008",  # function-call-in-default-argument
]

# Allow autofix for all enabled rules
fixable = ["ALL"]
unfixable = []

[format]
# Use double quotes for strings
quote-style = "double"

# Use spaces for indentation
indent-style = "space"

# Respect magic trailing commas
skip-magic-trailing-comma = false

